// export const mockCourses = [
//     {
//       id: 1,
//       title: "Complete Web Development Bootcamp",
//       instructor: "Dr. Angela Yu",
//       description: "Learn to build websites with HTML, CSS, JavaScript, React, Node, and more!",
//       longDescription:
//         "This comprehensive web development course is designed to take you from beginner to professional. You'll learn both front-end and back-end technologies, including HTML5, CSS3, JavaScript, React, Node.js, MongoDB, and more. By the end of this course, you'll be able to build complete, responsive websites and web applications from scratch.",
//       price: 99.99,
//       originalPrice: 199.99,
//       discount: 100,
//       rating: 4.8,
//       reviewCount: 45892,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Web Development",
//       type: "video",
//       isNew: true,
//       trending: true,
//       publishedDate: "2023-01-15",
//       lastUpdated: "2023-03-10",
//       duration: "63 hours",
//       lessons: 425,
//       learningPoints: [
//         "Build 16 web development projects for your portfolio",
//         "Learn the latest technologies, including Javascript, React, Node and MongoDB",
//         "Build fully-fledged websites and web apps for your startup or business",
//         "Master frontend development with React",
//         "Master backend development with Node",
//         "Learn professional developer best practices",
//       ],
//     },
//     {
//       id: 2,
//       title: "Machine Learning A-Z: Hands-On Python & R",
//       instructor: "Kirill Eremenko",
//       description: "Learn to create Machine Learning Algorithms in Python and R from scratch!",
//       longDescription:
//         "This course has been designed by two professional Data Scientists so that we can share our knowledge and help you learn complex theory, algorithms, and coding libraries in a simple way. We will walk you step-by-step into the World of Machine Learning. With every tutorial, you will develop new skills and improve your understanding of this challenging yet lucrative sub-field of Data Science.",
//       price: 129.99,
//       originalPrice: 199.99,
//       discount: 70,
//       rating: 4.6,
//       reviewCount: 32456,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Data Science",
//       type: "video",
//       isNew: false,
//       trending: true,
//       publishedDate: "2022-11-05",
//       lastUpdated: "2023-02-20",
//       duration: "44 hours",
//       lessons: 320,
//       learningPoints: [
//         "Master Machine Learning on Python & R",
//         "Have a great intuition of many Machine Learning models",
//         "Make accurate predictions with regression analysis",
//         "Make robust Machine Learning models",
//         "Use Machine Learning for personal purpose",
//         "Handle specific topics like Reinforcement Learning, NLP and Deep Learning",
//       ],
//     },
//     {
//       id: 3,
//       title: "The Complete Digital Marketing Course",
//       instructor: "Rob Percival",
//       description:
//         "Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More!",
//       longDescription:
//         "This complete digital marketing course is designed to help you become a successful digital marketer and grow your business or career. You'll learn all the key areas of digital marketing including SEO, social media marketing, email marketing, Google Analytics, and more. By the end of this course, you'll have the skills and knowledge to create effective digital marketing campaigns that drive results.",
//       price: 149.99,
//       originalPrice: 199.99,
//       discount: 50,
//       rating: 4.5,
//       reviewCount: 18734,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Marketing",
//       type: "video",
//       isNew: false,
//       trending: false,
//       publishedDate: "2022-08-12",
//       lastUpdated: "2023-01-05",
//       duration: "52 hours",
//       lessons: 380,
//       learningPoints: [
//         "Grow a business or brand from scratch",
//         "Get more sales & leads for your business",
//         "Master social media marketing on all major platforms",
//         "Learn SEO, SEM, YouTube marketing, email marketing, and more",
//         "Analyze your digital marketing results",
//         "Create a step-by-step digital marketing strategy",
//       ],
//     },
//     {
//       id: 4,
//       title: "iOS App Development Bootcamp",
//       instructor: "Dr. Angela Yu",
//       description:
//         "Learn to code and build iOS apps with Swift. Become an iOS developer from scratch with this complete course.",
//       longDescription:
//         "This iOS development course is the most comprehensive course available online. We'll take you from beginner with no programming experience to advanced iOS App Developer. You'll learn how to build beautiful iOS 16 apps for iPhone and iPad using Swift 5.5, Xcode 14, and Apple's latest UI Frameworks. By the end of this course, you'll be fluently programming in Swift and be ready to make your own apps or start a freelancing job as an iOS developer.",
//       price: 119.99,
//       originalPrice: 199.99,
//       discount: 80,
//       rating: 4.7,
//       reviewCount: 28945,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Mobile Development",
//       type: "video",
//       isNew: true,
//       trending: true,
//       publishedDate: "2023-02-01",
//       lastUpdated: "2023-03-15",
//       duration: "55 hours",
//       lessons: 410,
//       learningPoints: [
//         "Build over 20 fully-fledged apps including Uber and Instagram clones",
//         "Master Swift 5.5 and Xcode 14",
//         "Learn the fundamentals of programming and iOS development",
//         "Use ARKit to create augmented reality apps",
//         "Use CoreML & CreateML to build artificial intelligence apps",
//         "Submit your app to the App Store",
//       ],
//     },
//     {
//       id: 5,
//       title: "The Complete Financial Analyst Course",
//       instructor: "365 Careers",
//       description:
//         "Excel, Accounting, Financial Statement Analysis, Business Analysis, Financial Math, PowerPoint: Everything is Included!",
//       longDescription:
//         "This comprehensive financial analyst course will help you master financial analysis, modeling, and valuation. You'll learn Excel, accounting, financial statement analysis, business analysis, financial math, and PowerPoint. By the end of this course, you'll have the skills and knowledge to perform complex financial analysis and make informed investment decisions.",
//       price: 89.99,
//       originalPrice: 149.99,
//       discount: 60,
//       rating: 4.5,
//       reviewCount: 15678,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Finance",
//       type: "video",
//       isNew: false,
//       trending: false,
//       publishedDate: "2022-06-20",
//       lastUpdated: "2022-12-15",
//       duration: "25 hours",
//       lessons: 230,
//       learningPoints: [
//         "Build a strong foundation in Excel",
//         "Learn accounting, financial statement analysis, and business analysis",
//         "Master financial math concepts",
//         "Create professional PowerPoint presentations",
//         "Understand company valuation techniques",
//         "Analyze real-world financial data",
//       ],
//     },
//     {
//       id: 6,
//       title: "Complete Python Bootcamp: From Zero to Hero",
//       instructor: "Jose Portilla",
//       description:
//         "Learn Python like a Professional! Start from the basics and go all the way to creating your own applications and games!",
//       longDescription:
//         "This comprehensive Python course will take you from beginner to advanced level. You'll learn the Python 3 programming language from scratch, including object-oriented programming, error handling, modules, and much more. By the end of this course, you'll be able to create your own Python programs and applications, including games, web applications, and data analysis tools.",
//       price: 109.99,
//       originalPrice: 189.99,
//       discount: 80,
//       rating: 4.6,
//       reviewCount: 39567,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Programming",
//       type: "video",
//       isNew: false,
//       trending: true,
//       publishedDate: "2022-09-10",
//       lastUpdated: "2023-02-05",
//       duration: "35 hours",
//       lessons: 285,
//       learningPoints: [
//         "Learn to use Python professionally",
//         "Create games with Python, like Blackjack and Tic Tac Toe",
//         "Learn advanced Python features, like decorators and generators",
//         "Learn to use Object Oriented Programming with classes",
//         "Understand complex topics, like decorators",
//         "Build a complete understanding of Python from the ground up",
//       ],
//     },
//     {
//       id: 7,
//       title: "The Complete Graphic Design Course",
//       instructor: "Lindsay Marsh",
//       description:
//         "Learn Graphic Design in this course: Photoshop, InDesign, Illustrator, Design Theory, Branding and Logo Design",
//       longDescription:
//         "This comprehensive graphic design course will teach you everything you need to know to become a professional graphic designer. You'll learn industry-standard software like Photoshop, InDesign, and Illustrator, as well as design theory, branding, and logo design. By the end of this course, you'll have a strong portfolio of work and the skills to start a career in graphic design.",
//       price: 99.99,
//       originalPrice: 169.99,
//       discount: 70,
//       rating: 4.4,
//       reviewCount: 12456,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Design",
//       type: "video",
//       isNew: true,
//       trending: false,
//       publishedDate: "2023-01-25",
//       lastUpdated: "2023-03-01",
//       duration: "28 hours",
//       lessons: 210,
//       learningPoints: [
//         "Master Photoshop, InDesign, and Illustrator",
//         "Learn design theory and principles",
//         "Create professional logos and branding materials",
//         "Design marketing materials like flyers, brochures, and business cards",
//         "Understand typography and color theory",
//         "Build a professional portfolio of work",
//       ],
//     },
//     {
//       id: 8,
//       title: "The Complete 2023 Blockchain Development Bootcamp",
//       instructor: "Dr. Yu Zhang",
//       description: "Learn Solidity, Web3.js, Smart Contracts and Ethereum DApp Development",
//       longDescription:
//         "This comprehensive blockchain development course will teach you everything you need to know to become a blockchain developer. You'll learn Solidity programming, Web3.js, smart contracts, and Ethereum DApp development. By the end of this course, you'll be able to build decentralized applications on the Ethereum blockchain and understand the fundamentals of blockchain technology.",
//       price: 149.99,
//       originalPrice: 199.99,
//       discount: 50,
//       rating: 4.7,
//       reviewCount: 8765,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Blockchain",
//       type: "video",
//       isNew: true,
//       trending: true,
//       publishedDate: "2023-02-15",
//       lastUpdated: "2023-03-20",
//       duration: "32 hours",
//       lessons: 245,
//       learningPoints: [
//         "Build decentralized applications on the Ethereum blockchain",
//         "Write smart contracts with Solidity",
//         "Interact with smart contracts using Web3.js",
//         "Create, test and deploy DApps",
//         "Understand blockchain fundamentals",
//         "Learn about NFTs and DeFi applications",
//       ],
//     },
//     {
//       id: 9,
//       title: "Advanced UI/UX Design Masterclass",
//       instructor: "Sarah Johnson",
//       description: "Master modern UI/UX design principles, tools, and workflows to create stunning user experiences",
//       longDescription:
//         "This advanced UI/UX design course will take your design skills to the next level. You'll learn modern design principles, tools, and workflows to create stunning user experiences. The course covers user research, wireframing, prototyping, visual design, and usability testing. By the end, you'll have a professional portfolio showcasing your UI/UX design skills.",
//       price: 129.99,
//       originalPrice: 179.99,
//       discount: 50,
//       rating: 4.8,
//       reviewCount: 9876,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Design",
//       type: "video",
//       isNew: false,
//       trending: true,
//       publishedDate: "2022-12-10",
//       lastUpdated: "2023-02-28",
//       duration: "30 hours",
//       lessons: 220,
//       learningPoints: [
//         "Master Figma, Sketch, and Adobe XD",
//         "Conduct effective user research and testing",
//         "Create wireframes and interactive prototypes",
//         "Design responsive interfaces for web and mobile",
//         "Apply design thinking to solve complex problems",
//         "Build a professional UI/UX design portfolio",
//       ],
//     },
//     {
//       id: 10,
//       title: "Data Science and Machine Learning Bootcamp",
//       instructor: "Jose Marcial Portilla",
//       description:
//         "Complete Data Science Training: Mathematics, Statistics, Python, Advanced Statistics, Machine Learning",
//       longDescription:
//         "This comprehensive data science and machine learning bootcamp will teach you everything you need to know to become a data scientist. You'll learn mathematics, statistics, Python programming, advanced statistical analysis, and machine learning algorithms. By the end of this course, you'll be able to analyze data, build predictive models, and make data-driven decisions.",
//       price: 139.99,
//       originalPrice: 199.99,
//       discount: 60,
//       rating: 4.6,
//       reviewCount: 25678,
//       image: "/placeholder.svg?height=600&width=800",
//       category: "Data Science",
//       type: "video",
//       isNew: false,
//       trending: false,
//       publishedDate: "2022-10-05",
//       lastUpdated: "2023-01-20",
//       duration: "40 hours",
//       lessons: 300,
//       learningPoints: [
//         "Master Python for data science and machine learning",
//         "Learn statistical analysis and visualization",
//         "Build machine learning models with scikit-learn",
//         "Implement deep learning with TensorFlow and Keras",
//         "Work with real-world datasets and case studies",
//         "Create a portfolio of data science projects",
//       ],
//     },
//   ]
  
  