export const filterJobData = {
    remote: [
      { id: 1, title: 'Remote Software Engineer', company: 'TechCorp', description: 'Work from anywhere as a full-stack developer.', location: 'Anywhere, India', experience: '3+ years', salary: '₹7 LPA' },
      { id: 2, title: 'Remote Marketing Specialist', company: 'AdWiz', description: 'Join our marketing team and grow brands globally.', location: 'Anywhere, India', experience: '2+ years', salary: '₹6 LPA' },
      { id: 3, title: 'Remote Data Scientist', company: 'DataFlow', description: 'Analyze large datasets remotely to provide business insights.', location: 'Anywhere, India', experience: '4+ years', salary: '₹10 LPA' },
      { id: 4, title: 'Remote UX/UI Designer', company: 'DesignPro', description: 'Create beautiful and intuitive user interfaces for various apps.', location: 'Anywhere, India', experience: '2+ years', salary: '₹8 LPA' },
      { id: 5, title: 'Remote Copywriter', company: 'ContentCrafters', description: 'Write engaging content for digital marketing campaigns.', location: 'Anywhere, India', experience: '2+ years', salary: '₹5 LPA' },
    ],
    mnc: [
      { id: 1, title: 'Software Engineer - MNC', company: 'GlobalTech', description: 'Develop and maintain software for a global company.', location: 'Mumbai, India', experience: '3+ years', salary: '₹9 LPA' },
      { id: 2, title: 'Project Manager - MNC', company: 'WorldWide Ltd.', description: 'Manage software development projects for clients.', location: 'Bangalore, India', experience: '5+ years', salary: '₹12 LPA' },
      { id: 3, title: 'Cloud Architect', company: 'CloudWorks', description: 'Design cloud infrastructure for large multinational corporations.', location: 'Delhi, India', experience: '6+ years', salary: '₹15 LPA' },
      { id: 4, title: 'Senior HR Executive', company: 'TalentSoft', description: 'Lead HR initiatives for a multinational tech firm.', location: 'Chennai, India', experience: '5+ years', salary: '₹10 LPA' },
      { id: 5, title: 'Business Analyst', company: 'MNC Insights', description: 'Analyze and implement business solutions for international clients.', location: 'Pune, India', experience: '4+ years', salary: '₹8 LPA' },
    ],
    fresher: [
      { id: 1, title: 'Junior Developer - Fresher', company: 'Startup X', description: 'Kick-start your career as a software developer.', location: 'Noida, India', experience: 'Fresher', salary: '₹3 LPA' },
      { id: 2, title: 'HR Assistant - Fresher', company: 'Humanity Ltd.', description: 'Support HR team with recruitment and onboarding.', location: 'Gurgaon, India', experience: 'Fresher', salary: '₹2.5 LPA' },
      { id: 3, title: 'Digital Marketing Intern', company: 'AdGrowth', description: 'Assist the marketing team with campaign management and research.', location: 'Bangalore, India', experience: 'Fresher', salary: '₹2 LPA' },
      { id: 4, title: 'Content Writing Intern', company: 'Creative Content', description: 'Write engaging articles and blog posts for digital platforms.', location: 'Delhi, India', experience: 'Fresher', salary: '₹2.5 LPA' },
      { id: 5, title: 'Junior Graphic Designer', company: 'DesignHive', description: 'Assist in creating graphics for marketing and branding.', location: 'Pune, India', experience: 'Fresher', salary: '₹3 LPA' },
    ],
    // softwareIt: [
    //   { id: 1, title: 'Frontend Developer - IT', company: 'TechWorks', description: 'Develop user interfaces using ReactJS.', location: 'Hyderabad, India', experience: '3+ years', salary: '₹8 LPA' },
    //   { id: 2, title: 'Backend Developer - IT', company: 'CodeLabs', description: 'Work on server-side technologies like Node.js.', location: 'Mumbai, India', experience: '4+ years', salary: '₹9 LPA' },
    //   { id: 3, title: 'Full Stack Developer', company: 'FullStack Solutions', description: 'Build both frontend and backend of modern web apps.', location: 'Bangalore, India', experience: '5+ years', salary: '₹12 LPA' },
    //   { id: 4, title: 'DevOps Engineer', company: 'TechOps', description: 'Implement DevOps practices for continuous integration and delivery.', location: 'Chennai, India', experience: '4+ years', salary: '₹10 LPA' },
    //   { id: 5, title: 'Cloud Engineer', company: 'CloudPro', description: 'Manage cloud infrastructures and services for a growing business.', location: 'Delhi, India', experience: '4+ years', salary: '₹11 LPA' },
    // ],
    startup: [
      { id: 1, title: 'Startup Product Manager', company: 'NewCo', description: 'Work with founders to build a new product from scratch.', location: 'Bangalore, India', experience: '5+ years', salary: '₹10 LPA' },
      { id: 2, title: 'UI/UX Designer - Startup', company: 'DesignFlow', description: 'Design intuitive UI/UX for a new product.', location: 'Delhi, India', experience: '3+ years', salary: '₹8 LPA' },
      { id: 3, title: 'Startup Marketing Lead', company: 'GrowthHacker', description: 'Develop and execute marketing strategies for a new startup.', location: 'Chennai, India', experience: '4+ years', salary: '₹7.5 LPA' },
      { id: 4, title: 'Business Development Manager', company: 'Innovative Startups', description: 'Expand market reach and partnerships for a growing startup.', location: 'Pune, India', experience: '5+ years', salary: '₹9 LPA' },
      { id: 5, title: 'Co-Founder/CTO', company: 'Tech Innovators', description: 'Join as a CTO and co-founder to build the next big tech startup.', location: 'Mumbai, India', experience: '5+ years', salary: '₹15 LPA' },
    ],
    // supplyChain: [
    //   { id: 1, title: 'Supply Chain Manager', company: 'Logistics Pro', description: 'Manage the entire supply chain operations.', location: 'Delhi, India', experience: '5+ years', salary: '₹9 LPA' },
    //   { id: 2, title: 'Inventory Analyst', company: 'QuickGoods', description: 'Analyze inventory and optimize supply chain processes.', location: 'Mumbai, India', experience: '4+ years', salary: '₹7 LPA' },
    //   { id: 3, title: 'Supply Chain Coordinator', company: 'FastMovers', description: 'Coordinate the movement of goods from suppliers to customers.', location: 'Bangalore, India', experience: '3+ years', salary: '₹6 LPA' },
    //   { id: 4, title: 'Warehouse Operations Manager', company: 'StockUp', description: 'Manage daily warehouse operations and team performance.', location: 'Chennai, India', experience: '4+ years', salary: '₹7.5 LPA' },
    //   { id: 5, title: 'Procurement Specialist', company: 'ProcureWise', description: 'Handle procurement activities and supplier management.', location: 'Pune, India', experience: '3+ years', salary: '₹8 LPA' },
    // ],
    marketing: [
      { id: 1, title: 'Digital Marketing Executive', company: 'TechWave', description: 'Responsible for managing online campaigns and social media strategies.', location: 'Bangalore, India', experience: '2+ years', salary: '₹5 LPA' },
      { id: 2, title: 'Marketing Manager', company: 'AdWorks', description: 'Lead marketing initiatives and strategies to promote the brand.', location: 'Mumbai, India', experience: '5+ years', salary: '₹8 LPA' },
      { id: 3, title: 'SEO Specialist', company: 'SEO Hub', description: 'Optimize websites for better search engine ranking and traffic.', location: 'Delhi, India', experience: '3+ years', salary: '₹6 LPA' },
      { id: 4, title: 'Content Marketing Manager', company: 'ContentX', description: 'Oversee content creation and marketing campaigns.', location: 'Chennai, India', experience: '4+ years', salary: '₹7 LPA' },
      { id: 5, title: 'Graphic Designer', company: 'DesignPro', description: 'Create design assets for digital campaigns and projects.', location: 'Delhi, India', experience: '0-1 years', salary: '₹1.2 LPA' },
    ],
    internship: [
      { id: 1, title: 'Intern - Web Development', company: 'CodeLab', description: 'Work with the dev team on real-world projects.', location: 'Delhi, India', experience: 'Fresher', salary: '₹1.5 LPA' },
      { id: 2, title: 'Intern - Marketing', company: 'DigitalSpark', description: 'Learn and contribute to digital marketing campaigns.', location: 'Bangalore, India', experience: 'Fresher', salary: '₹1.2 LPA' },
      { id: 3, title: 'Business Development Intern', company: 'StartupHub', description: 'Assist in the growth and development of business strategies.', location: 'Mumbai, India', experience: 'Fresher', salary: '₹1 LPA' },
      { id: 4, title: 'Intern - Graphic Design', company: 'Creatify', description: 'Assist in designing marketing and social media content.', location: 'Chennai, India', experience: 'Fresher', salary: '₹1.2 LPA' },
      { id: 5, title: 'Intern - Content Writing', company: 'WriteSmart', description: 'Write blog posts and articles for digital marketing campaigns.', location: 'Pune, India', experience: 'Fresher', salary: '₹1.5 LPA' },
    ],
    analytics: [
      { id: 1, title: 'Data Analyst', company: 'DataVibe', description: 'Analyze large datasets to provide insights for business decisions.', location: 'Bangalore, India', experience: '3+ years', salary: '₹6 LPA' },
      { id: 2, title: 'Business Intelligence Analyst', company: 'DataLink', description: 'Provide actionable insights to enhance business processes.', location: 'Mumbai, India', experience: '4+ years', salary: '₹8 LPA' },
      { id: 3, title: 'Financial Analyst', company: 'FinSight', description: 'Provide financial analysis and support strategic decision-making.', location: 'Delhi, India', experience: '3+ years', salary: '₹7 LPA' },
      { id: 4, title: 'Marketing Analyst', company: 'AdMetrics', description: 'Analyze marketing data to drive better campaign performance.', location: 'Chennai, India', experience: '2+ years', salary: '₹5.5 LPA' },
      { id: 5, title: 'Product Analyst', company: 'Innovative Solutions', description: 'Analyze product performance and suggest improvements.', location: 'Pune, India', experience: '3+ years', salary: '₹7 LPA' },
    ],
    hr: [
      { id: 1, title: 'HR Executive', company: 'PeopleFirst', description: 'Handle employee recruitment, onboarding, and relations.', location: 'Delhi, India', experience: '3+ years', salary: '₹5.5 LPA' },
      { id: 2, title: 'HR Manager', company: 'CorpTalent', description: 'Manage HR operations and talent acquisition strategies.', location: 'Mumbai, India', experience: '4+ years', salary: '₹7 LPA' },
      { id: 3, title: 'Talent Acquisition Specialist', company: 'HireElite', description: 'Focus on recruiting top talent for the company.', location: 'Bangalore, India', experience: '3+ years', salary: '₹6.5 LPA' },
      { id: 4, title: 'HR Intern', company: 'HR Solutions', description: 'Assist the HR team in recruitment and other functions.', location: 'Chennai, India', experience: 'Fresher', salary: '₹1.8 LPA' },
      { id: 5, title: 'Payroll Specialist', company: 'PayrollPlus', description: 'Ensure accurate payroll processing for employees.', location: 'Pune, India', experience: '2+ years', salary: '₹5 LPA' },
    ],
    sales: [
      { id: 1, title: 'Sales Executive', company: 'SalesEdge', description: 'Drive sales and build relationships with clients.', location: 'Delhi, India', experience: '2+ years', salary: '₹5 LPA' },
      { id: 2, title: 'Account Manager', company: 'ClientConnect', description: 'Manage key accounts and lead the sales cycle.', location: 'Bangalore, India', experience: '3+ years', salary: '₹7 LPA' },
      { id: 3, title: 'Sales Manager', company: 'GrowthForce', description: 'Develop strategies to maximize sales and revenue.', location: 'Mumbai, India', experience: '4+ years', salary: '₹8.5 LPA' },
      { id: 4, title: 'Sales Intern', company: 'SalesBoost', description: 'Assist in sales activities and client communication.', location: 'Chennai, India', experience: 'Fresher', salary: '₹2 LPA' },
      { id: 5, title: 'Business Development Manager', company: 'BizGrowth', description: 'Expand new business opportunities and partnerships.', location: 'Pune, India', experience: '5+ years', salary: '₹9 LPA' },
    ],
  };
