export const filterJobData = {
  it: [
    {
      id: 1,
      title: 'Full-Stack Developer',
      company: 'TechCorp',
      description: 'Develop and maintain scalable web applications.',
      location: 'Bangalore, India',
      experience: '3+ years',
      salary: '₹12 LPA',
      responsibilities: [
        'Design and develop end-to-end features for web applications.',
        'Collaborate with UI/UX designers and backend teams.',
        'Write clean, efficient, and reusable code.',
      ],
      requirements: [
        'Proficiency in React, Node.js, and TypeScript.',
        'Experience with database systems like MongoDB and PostgreSQL.',
        'Knowledge of cloud platforms such as AWS or Azure.',
      ],
      skills: [
        'React', 'Node.js', 'TypeScript', 'MongoDB', 'PostgreSQL', 'AWS', 'Azure'
      ],
      application_deadline: "10-Dec-2025",
    },
    {
      id: 2,
      title: 'Frontend Developer',
      company: 'Innovatech',
      description: 'Craft responsive and high-performance user interfaces.',
      location: 'Hyderabad, India',
      experience: '2+ years',
      salary: '₹9 LPA',
      responsibilities: [
        'Develop responsive web interfaces using React and Tailwind CSS.',
        'Optimize UI components for performance and scalability.',
        'Collaborate with backend developers to integrate APIs.',
      ],
      requirements: [
        'Strong knowledge of JavaScript, HTML, and CSS.',
        'Experience with React and state management libraries like Redux.',
        'Good understanding of web performance optimization.',
      ],
      skills: [
        'JavaScript', 'HTML', 'CSS', 'React', 'Redux', 'Tailwind CSS'
      ],
      application_deadline: '15-Feb-2025',
    },
    {
      id: 3,
      title: 'DevOps Engineer',
      company: 'CloudWorks',
      description: 'Automate and optimize infrastructure for scalable systems.',
      location: 'Pune, India',
      experience: '4+ years',
      salary: '₹15 LPA',
      responsibilities: [
        'Build and maintain CI/CD pipelines.',
        'Monitor and troubleshoot production environments.',
        'Collaborate with development teams to improve deployment workflows.',
      ],
      requirements: [
        'Proficiency in Docker, Kubernetes, and Jenkins.',
        'Experience with infrastructure-as-code tools like Terraform.',
        'Strong understanding of cloud platforms (AWS, GCP).',
      ],
      skills: [
        'Docker', 'Kubernetes', 'Jenkins', 'Terraform', 'AWS', 'GCP'
      ],
      application_deadline: "10-Dec-2024",
    },
    {
      id: 4,
      title: 'Software Engineer (Backend)',
      company: 'CodeFlow',
      description: 'Design and implement efficient backend solutions.',
      location: 'Chennai, India',
      experience: '3+ years',
      salary: '₹13 LPA',
      responsibilities: [
        'Develop RESTful APIs and microservices.',
        'Ensure high availability and scalability of backend systems.',
        'Collaborate with frontend developers and stakeholders.',
      ],
      requirements: [
        'Strong programming skills in Python or Java.',
        'Experience with SQL and NoSQL databases.',
        'Familiarity with message queues like RabbitMQ or Kafka.',
      ],
      skills: [
        'Python', 'Java', 'SQL', 'NoSQL', 'RabbitMQ', 'Kafka'
      ],
      application_deadline: '10-Mar-2025',
    },
    {
      id: 5,
      title: 'Data Engineer',
      company: 'DataWave',
      description: 'Design and maintain data pipelines for analytics.',
      location: 'Mumbai, India',
      experience: '3+ years',
      salary: '₹14 LPA',
      responsibilities: [
        'Build and optimize ETL pipelines.',
        'Collaborate with data scientists to deliver datasets.',
        'Ensure data quality and consistency.',
      ],
      requirements: [
        'Proficiency in Python and SQL.',
        'Experience with Hadoop, Spark, or similar technologies.',
        'Strong understanding of data modeling and warehousing.',
      ],
      skills: [
        'Python', 'SQL', 'Hadoop', 'Spark', 'Data Modeling', 'Data Warehousing'
      ],
      application_deadline: "10-Dec-2025",
    },
    {
      id: 6,
      title: 'Product Manager',
      company: 'VisionaryTech',
      description: 'Lead cross-functional teams to deliver exceptional products.',
      location: 'Delhi, India',
      experience: '5+ years',
      salary: '₹18 LPA',
      responsibilities: [
        'Define and prioritize product roadmaps.',
        'Collaborate with engineering and design teams.',
        'Analyze user feedback and market trends.',
      ],
      requirements: [
        'Proven experience in product management.',
        'Strong understanding of Agile methodologies.',
        'Excellent communication and leadership skills.',
      ],
      skills: [
        'Product Management', 'Agile', 'Market', 'User Feedback Analysis'
      ],
      application_deadline: '10-Apr-2025',
      contact_email: 'pm-careers@visionarytech.com',
    },
    {
      id: 7,
      title: 'UI/UX Designer',
      company: 'CreativeX',
      description: 'Design intuitive and visually appealing user experiences.',
      location: 'Kolkata, India',
      experience: '2+ years',
      salary: '₹10 LPA',
      responsibilities: [
        'Create wireframes, prototypes, and mockups.',
        'Collaborate with developers to implement designs.',
        'Conduct user research and usability testing.',
      ],
      requirements: [
        'Proficiency in Figma, Adobe XD, and Sketch.',
        'Strong portfolio of UI/UX design work.',
        'Knowledge of design principles and accessibility standards.',
      ],
      skills: [
        'Figma', 'Adobe XD', 'Sketch', 'UI/UX Design', 'Accessibility Standards'
      ],
      application_deadline: "10-Jan-2025",
    }
  ],
  marketing: [
    {
      id: 1,
      title: 'Digital Marketing Executive',
      company: 'TechWave',
      description: 'Responsible for managing online campaigns, SEO, SEM, and social media strategies to drive brand growth and engagement.',
      location: 'Bangalore, India',
      experience: '2+ years',
      salary: '₹5 LPA',
      responsibilities: [
        'Plan and execute digital marketing campaigns, including SEO, PPC, email, and social media.',
        'Monitor and analyze campaign performance and optimize for better results.',
        'Develop and implement content strategies to increase brand awareness and engagement.',
        'Work closely with the content and design teams to create engaging marketing materials.',
        'Prepare and present reports on campaign performance and growth metrics.'
      ],
      requirements: [
        '2+ years of experience in digital marketing.',
        'Strong understanding of SEO, SEM, and social media marketing.',
        'Experience with Google Analytics, AdWords, and other marketing tools.',
        'Excellent communication and content creation skills.',
        'Ability to work in a fast-paced environment and meet deadlines.'
      ],
      skills: [
        'SEO', 'SEM', 'Google Analytics', 'AdWords', 'Content Creation', 'Social Media Marketing'
      ],
      application_deadline: '30th June 2025',
    },
    {
      id: 2,
      title: 'Marketing Manager',
      company: 'AdWorks',
      description: 'Lead marketing initiatives and strategies to promote the brand, drive customer acquisition, and improve brand positioning.',
      location: 'Mumbai, India',
      experience: '5+ years',
      salary: '₹8 LPA',
      responsibilities: [
        'Develop and implement comprehensive marketing strategies to drive growth.',
        'Lead and manage marketing campaigns, digital advertising, and market research.',
        'Analyze consumer trends and competitor strategies to identify growth opportunities.',
        'Collaborate with cross-functional teams, including product, design, and sales.',
        'Manage budgets, timelines, and resources for marketing projects.'
      ],
      requirements: [
        '5+ years of experience in marketing, with a proven track record of successful campaigns.',
        'Strong leadership and team management skills.',
        'Experience in content strategy, brand management, and customer acquisition.',
        'Proficiency in marketing tools such as Google Analytics, HubSpot, and social media platforms.',
        'Excellent analytical and communication skills.'
      ],
      skills: [
        'Content Strategy', 'Brand Management', 'Customer Acquisition', 'Google Analytics', 'HubSpot', 'Social Media Platforms'
      ],
      application_deadline: '15th July 2025',
    },
    {
      id: 3,
      title: 'SEO Specialist',
      company: 'SEO Hub',
      description: 'Optimize websites for better search engine ranking and traffic, focusing on keyword strategies and on-page optimization.',
      location: 'Delhi, India',
      experience: '3+ years',
      salary: '₹6 LPA',
      responsibilities: [
        'Conduct keyword research and implement on-page and off-page SEO strategies.',
        'Analyze website performance and improve search engine rankings.',
        'Collaborate with content teams to create SEO-friendly content.',
        'Monitor SEO trends and algorithm changes to stay ahead of industry shifts.',
        'Prepare SEO reports and provide insights on website traffic and keyword rankings.'
      ],
      requirements: [
        '3+ years of experience in SEO and digital marketing.',
        'Deep understanding of Google Analytics, Google Search Console, and SEO tools.',
        'Experience in keyword research, link building, and content optimization.',
        'Strong knowledge of SEO trends, algorithms, and best practices.',
        'Excellent problem-solving and analytical skills.'
      ],
      skills: [
        'Keyword Research', 'On-Page SEO', 'Off-Page SEO', 'Google Analytics', 'Google Search Console', 'Link Building'
      ],
      application_deadline: '5th August 2025',
    },
    {
      id: 4,
      title: 'Content Marketing Manager',
      company: 'ContentX',
      description: 'Oversee content creation and marketing campaigns, managing a team of content creators to produce engaging content for various digital platforms.',
      location: 'Chennai, India',
      experience: '4+ years',
      salary: '₹7 LPA',
      responsibilities: [
        'Develop content marketing strategies aligned with brand objectives.',
        'Lead the content team to produce blog posts, articles, videos, and other marketing materials.',
        'Collaborate with designers, social media teams, and product managers to ensure content is consistent and impactful.',
        'Measure and report on content performance and optimize strategies.',
        'Stay updated with the latest content marketing trends and technologies.'
      ],
      requirements: [
        '4+ years of experience in content marketing or digital marketing.',
        'Proven experience in leading content teams and developing content strategies.',
        'Excellent writing, editing, and proofreading skills.',
        'Familiarity with content management systems (CMS) and SEO principles.',
        'Strong communication and leadership skills.'
      ],
      skills: [
        'Content Marketing', 'Team Leadership', 'Writing', 'Editing', 'Proofreading', 'SEO'
      ],
      application_deadline: '10th August 2025',
    },
    {
      id: 5,
      title: 'Graphic Designer',
      company: 'DesignPro',
      description: 'Create design assets for digital campaigns, websites, and projects, focusing on creativity and visual communication.',
      location: 'Delhi, India',
      experience: '0-1 years',
      salary: '₹1.2 LPA',
      responsibilities: [
        'Design digital assets for web, social media, and print.',
        'Assist in developing visual concepts and brand identity.',
        'Collaborate with the marketing and content teams to create visually compelling designs.',
        'Ensure designs meet brand guidelines and are optimized for various platforms.',
        'Stay updated on design trends and best practices.'
      ],
      requirements: [
        '0-1 years of experience in graphic design.',
        'Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign).',
        'Strong understanding of design principles and visual communication.',
        'Creative mindset with attention to detail.',
        'Ability to work collaboratively and meet deadlines.'
      ],
      skills: [
        'Adobe Creative Suite', 'Photoshop', 'Illustrator', 'InDesign', 'Design Principles', 'Visual Communication'
      ],
      application_deadline: '20th August 2025',
    }
  ],
  analytics: [
    {
      id: 1,
      title: 'Data Analyst',
      company: 'DataVibe',
      description: 'Analyze large datasets to provide insights that support data-driven business decisions, and help in improving business strategies.',
      location: 'Bangalore, India',
      experience: '3+ years',
      salary: '₹6 LPA',
      responsibilities: [
        'Collect, clean, and analyze large datasets.',
        'Generate actionable insights and reports for business stakeholders.',
        'Work with business teams to understand data needs and provide solutions.',
        'Create dashboards and visualizations to represent data insights.',
        'Support decision-making by providing analytical support for business problems.'
      ],
      requirements: [
        'Strong proficiency in SQL, Excel, and data visualization tools (Tableau, Power BI).',
        'Experience with statistical tools like R or Python is a plus.',
        'Strong analytical and problem-solving skills.',
        'Ability to communicate complex data insights in simple terms.',
        'Attention to detail and ability to work independently.'
      ],
      application_deadline: '15th July 2025',
    },
    {
      id: 2,
      title: 'Business Intelligence Analyst',
      company: 'DataLink',
      description: 'Provide actionable insights to enhance business processes and improve efficiency using business intelligence tools and techniques.',
      location: 'Mumbai, India',
      experience: '4+ years',
      salary: '₹8 LPA',
      responsibilities: [
        'Design and develop BI solutions to support business decision-making.',
        'Work with business stakeholders to identify key metrics and KPIs.',
        'Create dashboards and reports to monitor business performance.',
        'Analyze complex data sets to derive actionable insights.',
        'Collaborate with IT teams to integrate BI systems with existing infrastructure.'
      ],
      requirements: [
        'Proficiency in BI tools such as Power BI, Tableau, or Qlik.',
        'Experience with data modeling, ETL processes, and data warehousing.',
        'Strong knowledge of SQL and data query languages.',
        'Excellent communication and presentation skills.',
        'Experience in business process analysis and improvement.'
      ],
      application_deadline: '20th July 2025',
    },
    {
      id: 3,
      title: 'Financial Analyst',
      company: 'FinSight',
      description: 'Provide financial analysis and support strategic decision-making by evaluating financial performance and forecasting future trends.',
      location: 'Delhi, India',
      experience: '3+ years',
      salary: '₹7 LPA',
      responsibilities: [
        'Conduct financial modeling and budgeting.',
        'Prepare financial reports and presentations for stakeholders.',
        'Analyze financial data to identify trends and provide insights.',
        'Support strategic planning with data-driven recommendations.',
        'Monitor financial performance against targets and suggest corrective actions.'
      ],
      requirements: [
        'Strong knowledge of financial modeling, budgeting, and forecasting.',
        'Proficiency in financial software (Excel, SAP, etc.) and reporting tools.',
        'Strong analytical and problem-solving skills.',
        'Excellent communication and presentation skills.',
        'Attention to detail and ability to meet deadlines.'
      ],
      application_deadline: '25th July 2025',
    },
    {
      id: 4,
      title: 'Marketing Analyst',
      company: 'AdMetrics',
      description: 'Analyze marketing data to drive better campaign performance and optimize marketing strategies.',
      location: 'Chennai, India',
      experience: '2+ years',
      salary: '₹5.5 LPA',
      responsibilities: [
        'Track and analyze marketing campaign performance.',
        'Conduct market research and competitor analysis.',
        'Create and maintain reports on marketing KPIs and ROI.',
        'Identify opportunities for campaign optimization.',
        'Work with marketing teams to refine strategies based on data insights.'
      ],
      requirements: [
        'Strong knowledge of digital marketing channels and analytics tools (Google Analytics, SEMrush, etc.).',
        'Proficiency in Excel or Google Sheets for data analysis.',
        'Good understanding of marketing trends and customer behavior.',
        'Ability to interpret data and present findings clearly.',
        'Excellent communication and teamwork skills.'
      ],
      application_deadline: '30th July 2025',
    },
    {
      id: 5,
      title: 'Product Analyst',
      company: 'Innovative Solutions',
      description: 'Analyze product performance and suggest improvements to help enhance the product and customer experience.',
      location: 'Pune, India',
      experience: '3+ years',
      salary: '₹7 LPA',
      responsibilities: [
        'Analyze product performance metrics and identify areas for improvement.',
        'Collaborate with product managers and engineers to enhance product features.',
        'Conduct user research and gather feedback to inform product decisions.',
        'Monitor product usage data and generate reports for stakeholders.',
        'Support the product development lifecycle by providing data-driven insights.'
      ],
      requirements: [
        'Experience with product analytics tools (Google Analytics, Mixpanel, etc.).',
        'Strong knowledge of product lifecycle management and metrics.',
        'Ability to analyze large sets of product data and derive actionable insights.',
        'Good understanding of customer behavior and user experience.',
        'Strong communication and collaboration skills.'
      ],
      application_deadline: '5th August 2025',
    }
  ],
    hr: [
      {
        id: 1,
        title: 'HR Manager',
        company: 'PeopleFirst',
        description: 'Oversee recruitment, employee relations, and organizational development.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹10 LPA',
        responsibilities: [
          'Manage end-to-end recruitment process.',
          'Develop and implement HR strategies and initiatives.',
          'Foster a positive and productive workplace culture.',
        ],
        requirements: [
          'Experience in HR management and leadership roles.',
          'Strong knowledge of labor laws and HR best practices.',
          'Excellent interpersonal and communication skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Flexible working hours.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'hr@peoplefirst.com',
      },
      {
        id: 2,
        title: 'Talent Acquisition Specialist',
        company: 'SkillUp',
        description: 'Focus on recruiting top talent across multiple roles and industries.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Screen resumes and conduct interviews for various positions.',
          'Build and maintain a strong candidate pipeline.',
          'Collaborate with hiring managers to define recruitment needs.',
        ],
        requirements: [
          'Experience in talent acquisition and recruiting.',
          'Familiarity with applicant tracking systems (ATS).',
          'Strong communication and negotiation skills.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with annual performance bonuses.',
          'Access to career development resources.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'HR Business Partner',
        company: 'GrowthHub',
        description: 'Act as a strategic partner to business leaders in driving people initiatives.',
        location: 'Hyderabad, India',
        experience: '7+ years',
        salary: '₹12 LPA',
        responsibilities: [
          'Partner with business leaders to address HR-related challenges.',
          'Develop and implement HR solutions aligned with business goals.',
          'Support organizational development and change management initiatives.',
        ],
        requirements: [
          'Strong experience in HR business partnering.',
          'Excellent problem-solving and strategic thinking abilities.',
          'Ability to influence and guide senior leadership.',
        ],
        perks: [
          'Stock options.',
          'Comprehensive health benefits.',
          'Paid parental leave.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Learning and Development Manager',
        company: 'EduCore',
        description: 'Lead the learning and development strategy to enhance employee skills.',
        location: 'Chennai, India',
        experience: '4+ years',
        salary: '₹11 LPA',
        responsibilities: [
          'Design and implement training programs for employee development.',
          'Identify skill gaps and create training solutions.',
          'Measure the effectiveness of training programs.',
        ],
        requirements: [
          'Experience in designing and implementing training programs.',
          'Strong understanding of learning management systems (LMS).',
          'Excellent communication and presentation skills.',
        ],
        perks: [
          'Education allowance.',
          'Opportunities for career growth and development.',
          'Health and wellness benefits.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Compensation and Benefits Specialist',
        company: 'CompensaCorp',
        description: 'Manage employee compensation and benefits programs to ensure competitiveness.',
        location: 'Pune, India',
        experience: '3+ years',
        salary: '₹9 LPA',
        responsibilities: [
          'Design and manage compensation structures and employee benefits.',
          'Analyze and benchmark compensation data to ensure competitiveness.',
          'Ensure compliance with applicable compensation and benefits regulations.',
        ],
        requirements: [
          'Experience in compensation and benefits management.',
          'Strong analytical and problem-solving skills.',
          'Familiarity with compensation software and HRIS systems.',
        ],
        perks: [
          'Performance-based bonuses.',
          'Comprehensive medical coverage.',
          'Retirement savings plan.',
        ],
        application_deadline: '15th March 2025',
      },
    ],    
    sales: [
      {
        id: 1,
        title: 'Sales Manager',
        company: 'SalesPro',
        description: 'Lead the sales team, drive revenue growth, and develop client relationships.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹12 LPA',
        skills: [
          'Sales Strategy', 'Team Management', 'Client Relationships'
        ],
        responsibilities: [
          'Develop and execute sales strategies to achieve business objectives.',
          'Manage and mentor the sales team to meet sales targets.',
          'Build and maintain strong relationships with key clients.',
        ],
        requirements: [
          'Proven experience in sales management.',
          'Strong leadership and team management skills.',
          'Excellent communication and negotiation skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Performance-based incentives.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'sales@salespro.com',
      },
      {
        id: 2,
        title: 'Account Executive',
        company: 'BizGrow',
        description: 'Drive sales and build long-term relationships with clients.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹8 LPA',
        skills: [ 
          'B2B Sales', 'Account Management', 'Lead Generation'
        ],
        responsibilities: [
          'Identify and acquire new business opportunities.',
          'Build strong relationships with clients to increase sales.',
          'Collaborate with the marketing team to generate leads.',
        ],
        requirements: [
          'Experience in B2B sales or account management.',
          'Strong presentation and communication skills.',
          'Ability to build rapport with clients and stakeholders.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Sales Operations Manager',
        company: 'TechSales',
        description: 'Optimize sales processes, improve efficiency, and support the sales team.',
        location: 'Hyderabad, India',
        experience: '7+ years',
        salary: '₹14 LPA',
        skills: [
          'Sales Operations', 'Process Improvement', 'Sales Analytics'
        ],
        responsibilities: [
          'Analyze and improve sales processes and operations.',
          'Support the sales team with tools, data, and insights.',
          'Coordinate sales campaigns and initiatives.',
        ],
        requirements: [
          'Experience in sales operations or similar roles.',
          'Strong analytical and problem-solving skills.',
          'Proficiency in CRM tools and sales analytics platforms.',
        ],
        perks: [
          'Stock options.',
          'Comprehensive health benefits.',
          'Flexible work hours.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Sales Executive',
        company: 'GrowFast',
        description: 'Generate leads and close deals to meet sales targets.',
        location: 'Chennai, India',
        experience: '2+ years',
        salary: '₹6 LPA',
        skills: [
          'Lead Generation', 'Sales Closing', 'Client Acquisition'
        ],
        responsibilities: [
          'Identify new business opportunities and lead generation.',
          'Close deals and manage client accounts.',
          'Achieve monthly and quarterly sales targets.',
        ],
        requirements: [
          'Experience in sales or lead generation.',
          'Strong communication and persuasion skills.',
          'Self-motivated and target-driven.',
        ],
        perks: [
          'Sales performance incentives.',
          'Training and development programs.',
          'Team bonding activities.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Regional Sales Manager',
        company: 'SalesForce',
        description: 'Oversee sales strategies across regions and manage sales teams.',
        location: 'Pune, India',
        experience: '6+ years',
        salary: '₹13 LPA',
        skills: [ 
          'Regional Sales', 'Team Management', 'Client Relationships'
        ],
        responsibilities: [
          'Develop and implement regional sales strategies.',
          'Manage and lead regional sales teams to exceed targets.',
          'Establish relationships with key clients and partners.',
        ],
        requirements: [
          'Extensive experience in regional sales management.',
          'Strong leadership and team management skills.',
          'Excellent strategic thinking and problem-solving skills.',
        ],
        perks: [
          'Annual performance bonuses.',
          'Company car and travel perks.',
          'Health insurance and retirement savings plans.',
        ],
        application_deadline: '15th March 2025',
      },
    ],    
    finance: [
      {
        id: 1,
        title: 'Finance Manager',
        company: 'FinCorp',
        description: 'Lead the finance team, manage budgeting, forecasting, and financial reporting.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹15 LPA',
        responsibilities: [
          'Oversee financial planning and analysis to support business decisions.',
          'Ensure compliance with financial regulations and standards.',
          'Manage cash flow, financial reporting, and budgeting.',
        ],
        requirements: [
          'Proven experience in finance management or similar roles.',
          'Strong knowledge of accounting and financial principles.',
          'Excellent analytical and problem-solving skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Performance-based incentives.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'finance@fincorp.com',
      },
      {
        id: 2,
        title: 'Financial Analyst',
        company: 'WealthTrack',
        description: 'Analyze financial data to support business decisions and strategy.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Prepare financial models and forecasts to guide decision-making.',
          'Analyze financial trends and provide insights to senior management.',
          'Support budgeting and financial planning processes.',
        ],
        requirements: [
          'Experience in financial analysis or related fields.',
          'Proficiency in financial modeling and Excel.',
          'Strong attention to detail and analytical skills.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Finance Operations Manager',
        company: 'MoneyMatters',
        description: 'Optimize financial operations, improve process efficiency, and manage a team.',
        location: 'Hyderabad, India',
        experience: '7+ years',
        salary: '₹18 LPA',
        responsibilities: [
          'Develop and improve financial reporting and operations processes.',
          'Support the finance team with tools and data for better decision-making.',
          'Ensure compliance with internal controls and audit standards.',
        ],
        requirements: [
          'Experience in finance operations or related fields.',
          'Strong leadership and management skills.',
          'Proficiency in financial software and reporting systems.',
        ],
        perks: [
          'Stock options.',
          'Comprehensive health benefits.',
          'Flexible work hours.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Tax Analyst',
        company: 'TaxPro',
        description: 'Manage tax filings, tax planning, and ensure compliance with tax regulations.',
        location: 'Chennai, India',
        experience: '3+ years',
        salary: '₹7 LPA',
        responsibilities: [
          'Prepare and file tax returns for individuals and businesses.',
          'Analyze tax regulations and provide guidance to the company.',
          'Assist in tax audits and represent the company before tax authorities.',
        ],
        requirements: [
          'Experience in tax preparation and compliance.',
          'Knowledge of tax laws and accounting principles.',
          'Attention to detail and strong problem-solving skills.',
        ],
        perks: [
          'Annual performance bonuses.',
          'Training and development programs.',
          'Health and wellness benefits.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Investment Analyst',
        company: 'InvestNow',
        description: 'Research and analyze investment opportunities and provide insights to clients.',
        location: 'Pune, India',
        experience: '4+ years',
        salary: '₹9 LPA',
        responsibilities: [
          'Conduct market research and investment analysis.',
          'Prepare reports and presentations for investment recommendations.',
          'Monitor portfolio performance and make adjustments as needed.',
        ],
        requirements: [
          'Experience in investment analysis or related fields.',
          'Strong analytical and research skills.',
          'Proficiency in financial tools and analysis software.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Opportunities for career growth and development.',
          'Retirement savings plan.',
        ],
        application_deadline: '15th March 2025',
      },
    ],    
    operations: [
      {
        id: 1,
        title: 'Operations Manager',
        company: 'OpEx Solutions',
        description: 'Lead the operations team, optimize processes, and ensure efficiency across the organization.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹14 LPA',
        responsibilities: [
          'Develop and implement operational strategies to improve business performance.',
          'Monitor and evaluate operational processes to ensure efficiency.',
          'Collaborate with department heads to align operations with company goals.',
        ],
        requirements: [
          'Proven experience in operations management or similar roles.',
          'Strong problem-solving and leadership skills.',
          'Experience in process improvement and project management.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance bonuses.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'operations@opexsolutions.com',
      },
      {
        id: 2,
        title: 'Supply Chain Coordinator',
        company: 'LogiTrack',
        description: 'Coordinate the end-to-end supply chain process, ensuring smooth and timely delivery of goods.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Monitor and manage inventory levels.',
          'Coordinate logistics and transportation activities.',
          'Work with vendors and suppliers to ensure timely deliveries.',
        ],
        requirements: [
          'Experience in supply chain management or related fields.',
          'Strong organizational and negotiation skills.',
          'Proficiency in supply chain management software.',
        ],
        perks: [
          'Remote work options.',
          'Performance-based incentives.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Operations Analyst',
        company: 'BusinessFlow',
        description: 'Analyze and optimize business operations to drive efficiency and reduce costs.',
        location: 'Hyderabad, India',
        experience: '4+ years',
        salary: '₹10 LPA',
        responsibilities: [
          'Analyze operational data and recommend process improvements.',
          'Support the operations team with data-driven insights.',
          'Prepare reports on key operational metrics and performance.',
        ],
        requirements: [
          'Experience in operations analysis or related fields.',
          'Proficiency in data analysis tools and techniques.',
          'Strong communication and analytical skills.',
        ],
        perks: [
          'Stock options.',
          'Flexible work hours.',
          'Health insurance benefits.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Logistics Manager',
        company: 'FastTrack Logistics',
        description: 'Manage the logistics operations and ensure efficient transportation and distribution processes.',
        location: 'Chennai, India',
        experience: '6+ years',
        salary: '₹12 LPA',
        responsibilities: [
          'Develop and implement logistics strategies to optimize supply chain performance.',
          'Oversee the transportation and distribution of goods.',
          'Ensure compliance with safety and regulatory standards in logistics.',
        ],
        requirements: [
          'Experience in logistics or supply chain management.',
          'Strong leadership and organizational skills.',
          'Ability to manage and improve logistics processes.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Training and development programs.',
          'Team bonding activities.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Operations Supervisor',
        company: 'OpEx Industries',
        description: 'Supervise daily operations, improve processes, and ensure smooth workflow across teams.',
        location: 'Pune, India',
        experience: '4+ years',
        salary: '₹9 LPA',
        responsibilities: [
          'Supervise day-to-day operations and ensure workflow efficiency.',
          'Coordinate between departments and address operational issues.',
          'Implement process improvements to optimize performance.',
        ],
        requirements: [
          'Experience in operations or team management.',
          'Strong leadership and multitasking skills.',
          'Ability to troubleshoot and solve operational issues.',
        ],
        perks: [
          'Performance-based bonuses.',
          'Opportunities for career growth and development.',
          'Retirement savings plan.',
        ],
        application_deadline: '15th March 2025',
      },
    ],    
    support: [
      {
        id: 1,
        title: 'Customer Support Manager',
        company: 'SupportHub',
        description: 'Lead the customer support team to ensure the highest level of service and satisfaction.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹12 LPA',
        responsibilities: [
          'Oversee customer support operations and ensure efficient handling of customer queries.',
          'Develop and implement customer support strategies to improve service quality.',
          'Train and manage customer support staff to maintain high performance.',
        ],
        requirements: [
          'Experience in customer service or support management.',
          'Strong leadership and communication skills.',
          'Ability to resolve customer issues effectively and efficiently.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Performance-based bonuses.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'support@supporthub.com',
      },
      {
        id: 2,
        title: 'Technical Support Specialist',
        company: 'TechAssist',
        description: 'Provide technical support to customers and resolve technical issues with products or services.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹7 LPA',
        responsibilities: [
          'Troubleshoot and resolve customer technical issues via phone, email, or chat.',
          'Document customer inquiries and technical issues for future reference.',
          'Collaborate with development teams to resolve complex technical issues.',
        ],
        requirements: [
          'Experience in technical support or IT helpdesk roles.',
          'Strong problem-solving and communication skills.',
          'Familiarity with troubleshooting software and hardware issues.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Customer Service Representative',
        company: 'ServicePro',
        description: 'Assist customers with product inquiries, issues, and provide top-notch support.',
        location: 'Hyderabad, India',
        experience: '2+ years',
        salary: '₹6 LPA',
        responsibilities: [
          'Handle customer inquiries and provide accurate information about products and services.',
          'Resolve customer complaints and escalate issues when necessary.',
          'Maintain customer records and document support interactions.',
        ],
        requirements: [
          'Experience in customer service or related roles.',
          'Excellent communication and interpersonal skills.',
          'Strong attention to detail and ability to multitask.',
        ],
        perks: [
          'Health and wellness benefits.',
          'Annual performance bonuses.',
          'Opportunities for career growth.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Help Desk Support Specialist',
        company: 'SupportTech',
        description: 'Provide front-line technical support for IT issues and assist in troubleshooting system problems.',
        location: 'Chennai, India',
        experience: '4+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Provide IT support for employees and external customers.',
          'Respond to help desk tickets and provide timely resolutions.',
          'Maintain and update IT documentation for troubleshooting procedures.',
        ],
        requirements: [
          'Experience in IT support or helpdesk roles.',
          'Proficiency in troubleshooting hardware and software issues.',
          'Strong communication and problem-solving skills.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Flexible working hours.',
          'Employee wellness programs.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Client Support Specialist',
        company: 'ClientFirst',
        description: 'Provide ongoing support to clients, ensuring satisfaction and resolution of issues.',
        location: 'Pune, India',
        experience: '3+ years',
        salary: '₹7.5 LPA',
        responsibilities: [
          'Provide support to clients via email, phone, or live chat.',
          'Address client inquiries and resolve issues in a timely manner.',
          'Collaborate with other departments to ensure customer satisfaction.',
        ],
        requirements: [
          'Experience in client or customer support roles.',
          'Excellent communication and organizational skills.',
          'Ability to work well under pressure and meet deadlines.',
        ],
        perks: [
          'Retirement savings plan.',
          'Performance-based incentives.',
          'Career development opportunities.',
        ],
        application_deadline: '15th March 2025',
      },
    ],    
    legal: [
      {
        id: 1,
        title: 'Legal Counsel',
        company: 'LawCorp',
        description: 'Provide legal guidance to the organization, manage contracts, and ensure compliance with laws and regulations.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹20 LPA',
        responsibilities: [
          'Draft, review, and negotiate contracts and agreements.',
          'Ensure compliance with local and international laws and regulations.',
          'Provide legal advice to senior management on business operations.',
        ],
        requirements: [
          'Law degree with specialization in corporate or business law.',
          'Strong negotiation and communication skills.',
          'Experience in handling complex legal issues and disputes.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance-based bonuses.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'legal@lawcorp.com',
      },
      {
        id: 2,
        title: 'Corporate Legal Advisor',
        company: 'FinLaw Advisors',
        description: 'Provide strategic legal advice to clients on corporate governance, mergers, acquisitions, and other legal matters.',
        location: 'Mumbai, India',
        experience: '6+ years',
        salary: '₹25 LPA',
        responsibilities: [
          'Advise clients on corporate governance and compliance matters.',
          'Manage mergers, acquisitions, and joint ventures.',
          'Draft and review corporate contracts and agreements.',
        ],
        requirements: [
          'Bachelor’s degree in law, with a focus on corporate law.',
          'Experience in corporate law, mergers, and acquisitions.',
          'Excellent analytical and communication skills.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Legal Assistant',
        company: 'Justice Partners',
        description: 'Assist the legal team with research, document preparation, and case management.',
        location: 'Hyderabad, India',
        experience: '2+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Conduct legal research and assist in preparing legal documents.',
          'Maintain case files and documentation.',
          'Assist lawyers with case management and court preparations.',
        ],
        requirements: [
          'Degree in law or paralegal studies.',
          'Strong research and organizational skills.',
          'Ability to manage multiple tasks and meet deadlines.',
        ],
        perks: [
          'Health insurance benefits.',
          'Annual performance bonuses.',
          'Opportunities for career growth and development.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Contract Manager',
        company: 'LegalWorks',
        description: 'Oversee and manage the organization’s contracts, ensuring legal compliance and minimizing risk.',
        location: 'Chennai, India',
        experience: '4+ years',
        salary: '₹15 LPA',
        responsibilities: [
          'Draft, review, and manage contracts with clients and vendors.',
          'Ensure contracts comply with legal regulations and organizational policies.',
          'Negotiate terms and resolve contract disputes.',
        ],
        requirements: [
          'Degree in law, with experience in contract management.',
          'Strong attention to detail and negotiation skills.',
          'Experience in managing high-value contracts.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Flexible working hours.',
          'Employee wellness programs.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Litigation Associate',
        company: 'LegalEagle Law Firm',
        description: 'Represent clients in court, manage litigation cases, and provide legal counsel during trial proceedings.',
        location: 'Pune, India',
        experience: '3+ years',
        salary: '₹18 LPA',
        responsibilities: [
          'Represent clients in court hearings and trials.',
          'Prepare and file legal documents and petitions.',
          'Conduct legal research and advise clients on litigation strategy.',
        ],
        requirements: [
          'Law degree with specialization in litigation or criminal law.',
          'Experience in court proceedings and handling litigation cases.',
          'Strong advocacy and communication skills.',
        ],
        perks: [
          'Retirement savings plan.',
          'Performance-based incentives.',
          'Career development opportunities.',
        ],
        application_deadline: '15th March 2025',
      },
    ],  
    training: [
      {
        id: 1,
        title: 'Corporate Trainer',
        company: 'SkillTech Training Solutions',
        description: 'Conduct corporate training sessions to enhance employee skills and boost organizational performance.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹12 LPA',
        responsibilities: [
          'Develop and deliver training programs on various corporate skills.',
          'Assess employee skills and design personalized training modules.',
          'Collaborate with department heads to ensure alignment of training programs with company goals.',
        ],
        requirements: [
          'Proven experience in corporate training or learning and development.',
          'Excellent communication and presentation skills.',
          'Ability to engage and motivate employees during training sessions.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance-based bonuses.',
          'Employee wellness programs.',
        ],
        application_deadline: '15th January 2025',
        contact_email: 'training@skilltech.com',
      },
      {
        id: 2,
        title: 'Soft Skills Trainer',
        company: 'TalentTrain Academy',
        description: 'Conduct soft skills training to improve communication, teamwork, and leadership abilities within teams.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Design and deliver soft skills training programs such as communication, leadership, and interpersonal skills.',
          'Evaluate employee progress and provide feedback.',
          'Customize training programs to meet the needs of different teams.',
        ],
        requirements: [
          'Experience in teaching soft skills or related fields.',
          'Strong interpersonal and communication skills.',
          'Ability to assess and improve employee soft skills effectively.',
        ],
        perks: [
          'Remote work options.',
          'Competitive salary with performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '30th January 2025',
      },
      {
        id: 3,
        title: 'Technical Trainer',
        company: 'TechSkill Academy',
        description: 'Train employees or clients in technical skills and software tools to ensure proficiency and performance.',
        location: 'Hyderabad, India',
        experience: '4+ years',
        salary: '₹10 LPA',
        responsibilities: [
          'Deliver training sessions on technical topics, including software, programming, and IT systems.',
          'Create training materials, manuals, and resources.',
          'Stay updated on emerging technologies and incorporate them into training programs.',
        ],
        requirements: [
          'Proven experience as a technical trainer or in a similar role.',
          'Deep understanding of relevant technologies and tools.',
          'Ability to explain complex technical concepts in an easy-to-understand manner.',
        ],
        perks: [
          'Health and wellness benefits.',
          'Annual performance bonuses.',
          'Opportunities for career growth.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 4,
        title: 'Training Coordinator',
        company: 'EduGrowth Solutions',
        description: 'Coordinate and organize training programs, ensuring the smooth execution and tracking of employee progress.',
        location: 'Chennai, India',
        experience: '3+ years',
        salary: '₹9 LPA',
        responsibilities: [
          'Schedule and coordinate training sessions and workshops.',
          'Maintain training records and track employee progress.',
          'Collaborate with trainers to ensure high-quality training delivery.',
        ],
        requirements: [
          'Experience in training coordination or administration.',
          'Excellent organizational and communication skills.',
          'Ability to manage multiple tasks and prioritize effectively.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Flexible working hours.',
          'Employee wellness programs.',
        ],
        application_deadline: '28th February 2025',
      },
      {
        id: 5,
        title: 'Leadership Development Trainer',
        company: 'LeadPath Institute',
        description: 'Provide leadership development training to high-potential employees, preparing them for management roles.',
        location: 'Pune, India',
        experience: '6+ years',
        salary: '₹15 LPA',
        responsibilities: [
          'Develop and deliver leadership training programs for mid-level management.',
          'Evaluate and assess employees’ leadership potential.',
          'Work with HR and senior leadership to identify training needs.',
        ],
        requirements: [
          'Proven experience in leadership training or development.',
          'Strong understanding of leadership theories and practices.',
          'Ability to inspire and coach future leaders.',
        ],
        perks: [
          'Retirement savings plan.',
          'Performance-based incentives.',
          'Career development opportunities.',
        ],
        application_deadline: '15th March 2025',
      },
    ],      
    engineering: [
      {
        id: 1,
        title: 'Software Engineer',
        company: 'TechSoft Solutions',
        description: 'Develop, test, and maintain software applications to meet business needs.',
        location: 'Bangalore, India',
        experience: '3+ years',
        salary: '₹15 LPA',
        responsibilities: [
          'Design, develop, and deploy software solutions.',
          'Collaborate with cross-functional teams to define requirements and specifications.',
          'Write clean, maintainable, and efficient code.',
        ],
        requirements: [
          'Proven experience as a software engineer or similar role.',
          'Strong knowledge of programming languages such as Java, Python, or C++.',
          'Familiarity with software development methodologies (Agile, Scrum).',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance-based bonuses.',
          'Work-from-home options.',
        ],
        application_deadline: '20th January 2025',
        contact_email: 'careers@techsoft.com',
      },
      {
        id: 2,
        title: 'Civil Engineer',
        company: 'ConstructPro Ltd.',
        description: 'Design, plan, and manage civil engineering projects including roads, bridges, and buildings.',
        location: 'Mumbai, India',
        experience: '4+ years',
        salary: '₹18 LPA',
        responsibilities: [
          'Create detailed plans and designs for infrastructure projects.',
          'Supervise construction sites and ensure adherence to specifications.',
          'Collaborate with architects, contractors, and other engineers.',
        ],
        requirements: [
          'Bachelor’s degree in Civil Engineering or related field.',
          'Experience with design software like AutoCAD or Civil 3D.',
          'Strong understanding of construction processes and safety standards.',
        ],
        perks: [
          'Health and wellness benefits.',
          'Career advancement opportunities.',
          'Annual performance bonuses.',
        ],
        application_deadline: '10th February 2025',
      },
      {
        id: 3,
        title: 'Mechanical Engineer',
        company: 'MechTech Industries',
        description: 'Design and develop mechanical systems and devices for various industrial applications.',
        location: 'Hyderabad, India',
        experience: '5+ years',
        salary: '₹20 LPA',
        responsibilities: [
          'Design mechanical systems and components for manufacturing.',
          'Conduct tests and simulations to ensure optimal performance.',
          'Work closely with production teams to ensure designs are feasible and efficient.',
        ],
        requirements: [
          'Bachelor’s degree in Mechanical Engineering.',
          'Experience with CAD software such as SolidWorks or AutoCAD.',
          'Strong analytical and problem-solving skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Employee wellness programs.',
          'Annual performance-based bonuses.',
        ],
        application_deadline: '5th March 2025',
      },
      {
        id: 4,
        title: 'Electrical Engineer',
        company: 'PowerGrid Technologies',
        description: 'Design, implement, and maintain electrical systems for power generation and distribution.',
        location: 'Chennai, India',
        experience: '3+ years',
        salary: '₹17 LPA',
        responsibilities: [
          'Design electrical circuits and systems for various applications.',
          'Test and troubleshoot electrical systems to ensure safety and efficiency.',
          'Collaborate with other engineering teams to integrate electrical components.',
        ],
        requirements: [
          'Bachelor’s degree in Electrical Engineering.',
          'Knowledge of electrical design software and tools.',
          'Strong understanding of electrical safety standards.',
        ],
        perks: [
          'Retirement savings plan.',
          'Flexible working hours.',
          'Health and wellness benefits.',
        ],
        application_deadline: '20th March 2025',
      },
      {
        id: 5,
        title: 'Chemical Engineer',
        company: 'ChemTech Innovations',
        description: 'Develop processes and systems for large-scale manufacturing in the chemical industry.',
        location: 'Pune, India',
        experience: '6+ years',
        salary: '₹22 LPA',
        responsibilities: [
          'Design and optimize chemical production processes.',
          'Ensure safety and compliance with environmental regulations.',
          'Collaborate with cross-functional teams to improve process efficiency.',
        ],
        requirements: [
          'Bachelor’s degree in Chemical Engineering or related field.',
          'Experience with process simulation software and chemical analysis.',
          'Strong problem-solving and analytical skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance-based bonuses.',
          'Career development opportunities.',
        ],
        application_deadline: '15th April 2025',
      },
    ],    
    administration: [
      {
        id: 1,
        title: 'Administration Manager',
        company: 'AdminPro Solutions',
        description: 'Lead the administration team to ensure smooth operations and effective office management.',
        location: 'Bangalore, India',
        experience: '5+ years',
        salary: '₹14 LPA',
        responsibilities: [
          'Oversee day-to-day office operations and administrative functions.',
          'Manage office supplies, vendor relationships, and office logistics.',
          'Coordinate and support executive teams in various administrative tasks.',
        ],
        requirements: [
          'Proven experience in office administration or facilities management.',
          'Strong organizational and multitasking skills.',
          'Excellent communication and interpersonal skills.',
        ],
        perks: [
          'Health insurance for employees and families.',
          'Annual performance-based bonuses.',
          'Work-from-home flexibility.',
        ],
        application_deadline: '10th January 2025',
        contact_email: 'careers@adminpro.com',
      },
      {
        id: 2,
        title: 'Office Administrator',
        company: 'OfficeFlow Services',
        description: 'Ensure the smooth running of office operations by handling administrative tasks and supporting staff needs.',
        location: 'Mumbai, India',
        experience: '3+ years',
        salary: '₹10 LPA',
        responsibilities: [
          'Manage office schedules, meetings, and communications.',
          'Assist in coordinating office events, conferences, and team-building activities.',
          'Handle incoming calls, emails, and other communications for office staff.',
        ],
        requirements: [
          'Experience in administrative or office management roles.',
          'Strong organizational, communication, and problem-solving skills.',
          'Proficiency in MS Office and office management software.',
        ],
        perks: [
          'Flexible work hours.',
          'Competitive salary with performance-based incentives.',
          'Opportunities for career growth and advancement.',
        ],
        application_deadline: '25th January 2025',
      },
      {
        id: 3,
        title: 'Executive Assistant',
        company: 'Corporate Assist',
        description: 'Provide high-level administrative support to executives and ensure efficient office functioning.',
        location: 'Hyderabad, India',
        experience: '4+ years',
        salary: '₹13 LPA',
        responsibilities: [
          'Manage executive calendars, schedules, and appointments.',
          'Coordinate travel arrangements and prepare expense reports.',
          'Assist with meetings, presentations, and correspondence.',
        ],
        requirements: [
          'Experience as an executive assistant or in a similar administrative role.',
          'Excellent organizational and time management skills.',
          'Strong written and verbal communication skills.',
        ],
        perks: [
          'Health and wellness benefits.',
          'Annual performance bonuses.',
          'Opportunities for career development.',
        ],
        application_deadline: '5th February 2025',
      },
      {
        id: 4,
        title: 'Office Support Specialist',
        company: 'Efficient Offices',
        description: 'Support the office team by managing administrative tasks, providing customer service, and maintaining office operations.',
        location: 'Chennai, India',
        experience: '2+ years',
        salary: '₹8 LPA',
        responsibilities: [
          'Handle office supplies, ordering, and inventory management.',
          'Assist with client inquiries and office-related customer service tasks.',
          'Ensure office equipment and facilities are well-maintained.',
        ],
        requirements: [
          'Experience in office administration or customer service.',
          'Strong communication and organizational skills.',
          'Ability to handle office equipment and maintain cleanliness.',
        ],
        perks: [
          'Annual performance-based bonuses.',
          'Flexible working hours.',
          'Employee wellness programs.',
        ],
        application_deadline: '20th February 2025',
      },
      {
        id: 5,
        title: 'Administrative Assistant',
        company: 'AdminExperts',
        description: 'Support office operations with clerical and administrative tasks, ensuring smooth and efficient workflow.',
        location: 'Pune, India',
        experience: '1+ years',
        salary: '₹6 LPA',
        responsibilities: [
          'Assist in office scheduling and daily administrative operations.',
          'Provide support to senior management and team members.',
          'Maintain office files and records, ensuring proper organization.',
        ],
        requirements: [
          'Experience in administrative roles.',
          'Strong organizational and multitasking skills.',
          'Proficiency in office software and data management.',
        ],
        perks: [
          'Health insurance.',
          'Career growth opportunities.',
          'Employee perks and discounts.',
        ],
        application_deadline: '10th March 2025',
      },
    ]    
  };



  export const companyLogos = {
    TechCorp: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1280px-Infosys_logo.svg.png",
    Innovatech:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/2560px-Tata_Consultancy_Services_Logo.svg.png",
    CloudWorks:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/2560px-Wipro_Primary_Logo_Color_RGB.svg.png",
    CodeFlow:
      "https://www.hcltech.com/themes/custom/hcltech/images/hcltech-new-logo.svg",
    DataWave: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/2560px-Accenture.svg.png",
    VisionaryTech:
      "https://www.capgemini.com/wp-content/themes/capgemini2020/assets/images/logo.svg",
    CreativeX:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Google_Cloud_logo.svg/2560px-Google_Cloud_logo.svg.png",
    "Amazon Web Services":
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/2560px-Amazon_Web_Services_Logo.svg.png",
  }